# Generated by Django 2.2.28 on 2023-06-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='title',
        ),
    ]
