# Generated by Django 2.2.28 on 2023-06-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230623_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='title2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
