# Generated by Django 2.2.28 on 2023-06-26 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_title2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='title2',
        ),
    ]
